/**
 * feedGenerator.js
 * Builds and uploads a W3C-valid RSS 2.0 feed using rewritten articles.
 */

import crypto from "crypto";
import { XMLBuilder } from "fast-xml-parser";
import { r2Put } from "../../shared/utils/r2-client.js";
import { info, error } from "#logger.js";

export async function generateFeed(bucket, rewrittenItems) {
  try {
    if (!Array.isArray(rewrittenItems) || rewrittenItems.length === 0) {
      info("rss-feed-creator.generateFeed.skip", { reason: "no items" });
      return;
    }

    const now = new Date();
    const buildDate = now.toUTCString();

    // ✅ Use environment configuration
    const channelTitle =
      process.env.RSS_FEED_TITLE?.trim() || "Turing’s Torch: AI Weekly";
    const channelLink = "https://jonathan-harris.online";
    const channelDesc =
      process.env.RSS_FEED_DESCRIPTION?.trim() ||
      "AI insights and rewritten articles generated by Jonathan Harris’s AI Podcast Suite.";

    const validItems = rewrittenItems.filter(
      (x) => x && typeof x === "object"
    );

    const feedObj = {
      rss: {
        "@_version": "2.0",
        channel: {
          title: sanitizeText(channelTitle),
          link: channelLink,
          description: sanitizeText(channelDesc),
          language: "en-gb",
          lastBuildDate: buildDate,
          pubDate: buildDate,
          generator: "AI Podcast Suite - RSS Feed Creator",
          item: validItems.map((item) => ({
            // ✅ Prefer AI short title, fallback to rewritten title, fallback to source
            title: sanitizeText(
              item.shortTitle || item.title || "Untitled Article"
            ),

            // ✅ Prefer short URL (Short.io), fallback to link or homepage
            link: sanitizeUrl(
              item.shortUrl || item.link || channelLink
            ),

            guid: sanitizeUrl(
              item.shortGuid ||
              item.guid ||
              item.link ||
              crypto.randomUUID()
            ),

            pubDate: new Date(item.pubDate || now).toUTCString(),

            // ✅ Always use rewritten text if available
            description: wrapCData(
              sanitizeText(item.rewritten || item.summary || "")
            ),
          })),
        },
      },
    };

    const builder = new XMLBuilder({
      format: true,
      ignoreAttributes: false,
      suppressEmptyNode: true,
    });

    const xmlString =
      '<?xml version="1.0" encoding="UTF-8"?>\n' + builder.build(feedObj);
    const jsonString = JSON.stringify(feedObj, null, 2);

    // ✅ Upload both XML and JSON to R2
    await r2Put(bucket, "feed.xml", xmlString, "application/rss+xml");
    await r2Put(bucket, "feed.json", jsonString, "application/json");

    info("rss-feed-creator.generateFeed.success", {
      bucket,
      items: validItems.length,
      size: xmlString.length,
    });
  } catch (err) {
    error("rss-feed-creator.generateFeed.fail", err, { bucket });
  }
}

// ─────────────────────────────────────────────
// 🔧 Helpers
// ─────────────────────────────────────────────

function sanitizeText(str) {
  if (typeof str !== "string") {
    try {
      str = JSON.stringify(str);
    } catch {
      str = String(str ?? "");
    }
  }

  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;")
    .trim();
}

function sanitizeUrl(url = "") {
  if (!url) return "";
  try {
    return new URL(url).href;
  } catch {
    return "";
  }
}

function wrapCData(text = "") {
  const safeText = text.replaceAll("]]>", "]]]]><![CDATA[>");
  return `<![CDATA[${safeText}]]>`;
      }
