/**
 * feedGenerator.js
 * Builds and uploads a W3C-valid RSS 2.0 feed using rewritten articles.
 */

import { XMLBuilder } from "fast-xml-parser";
import { r2Put } from "../../shared/utils/r2-client.js";
import { logInfo, logError } from "../../shared/utils/logger.js";

export async function generateFeed(bucket, rewrittenItems) {
  try {
    if (!Array.isArray(rewrittenItems) || rewrittenItems.length === 0) {
      logInfo("rss-feed-creator.generateFeed.skip", { reason: "no items" });
      return;
    }

    const now = new Date();
    const buildDate = now.toUTCString();

    const channelTitle = "daily artificial news updates with a gen x twist";
    const channelLink = "https://jonathan-harris.online";
    const channelDesc =
      "AI insights and rewritten articles generated by Jonathan Harris.";

    const feedObj = {
      rss: {
        "@_version": "2.0",
        channel: {
          title: channelTitle,
          link: channelLink,
          description: channelDesc,
          language: "en-gb",
          lastBuildDate: buildDate,
          pubDate: buildDate,
          generator: "AI Podcast Suite - RSS Feed Creator",
          item: rewrittenItems.map((item) => ({
            title: sanitizeText(item.title || "Untitled Article"),
            link: sanitizeUrl(item.link || channelLink),
            guid: sanitizeUrl(item.guid || item.link || crypto.randomUUID()),
            pubDate: new Date(item.pubDate || now).toUTCString(),
            description: wrapCData(
              sanitizeText(item.rewritten || item.summary || "")
            ),
          })),
        },
      },
    };

    const builder = new XMLBuilder({
      format: true,
      ignoreAttributes: false,
      suppressEmptyNode: true,
    });

    const xmlString =
      '<?xml version="1.0" encoding="UTF-8"?>\n' + builder.build(feedObj);
    const jsonString = JSON.stringify(feedObj, null, 2);

    // Upload RSS + JSON to R2
    await r2Put(bucket, "feed.xml", xmlString, "application/rss+xml");
    await r2Put(bucket, "feed.json", jsonString, "application/json");

    logInfo("rss-feed-creator.generateFeed.success", {
      bucket,
      items: rewrittenItems.length,
      size: xmlString.length,
    });
  } catch (err) {
    logError("rss-feed-creator.generateFeed.fail", err, { bucket });
  }
}

// --- Helpers ---

function sanitizeText(str = "") {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;")
    .trim();
}

function sanitizeUrl(url = "") {
  if (!url) return "";
  try {
    return new URL(url).href;
  } catch {
    return "";
  }
}

function wrapCData(text = "") {
  // Prevent CDATA breaks by escaping nested sequences
  const safeText = text.replaceAll("]]>", "]]]]><![CDATA[>");
  return `<![CDATA[${safeText}]]>`;
    }
